require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - "db/**/*"
  TargetRubyVersion: 2.7.2

###
### Metrics
###
Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

###
### Lint
###
Lint/RequireParentheses:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

###
### Style
###
Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false

Style/NumericLiterals:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/RegexpLiteral:
  AllowInnerSlashes: true
  EnforcedStyle: slashes

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

###
### Layout
###
Layout/EndAlignment:
  AutoCorrect: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

###
### Rails
###
Rails/Output:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/HttpStatus:
  EnforcedStyle: numeric

###
### Rspec
###
RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/LetBeforeExamples:
  Enabled: false
